### ISSUE TITLE
Cannot build after cleaning the solution.

### ISSUE THREAD

**Issue by forlayo** [araditc/Artalk.Xmpp#12]
**Describe the bug**
Cleaning the solution, removes Interop.UPNPLib.dll which was added as a binary file directly at obj directory. Could we have the project or nuget package that match this file ?

**To Reproduce**
1.- Clean the solution through VS menu or remove bin/obj directories.
2.- Build the solution.
3.- See that the solution is not compiling and asking about missing UPNPLib library.

**Expected behavior**
Cleaning solution and compiling without any issues.

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version 10 (2004)

**Comment by ammarheidari** [comment]
Hello
Please check again

**Comment by forlayo** [comment]
@ammarheidari now it works perfectly, thanks also for updating the nuget package.
