### ISSUE TITLE
Can not resolve reference: `Interop.UPNPLib`

### ISSUE THREAD

**Issue by shysd** [araditc/Artalk.Xmpp#14]
**Describe the bug**
Interop.UPNPLib cannot be resolved while building the project

**To Reproduce**
1. Install Artalk.Xmpp from NuGet package manager
2. in MainPage.xaml.cs `using Artalk.Xmpp.Client`
3. in primary class `ArtalkXmppClient client = new ArtalkXmppClient(host, user, pass);`
4. Build solution, see error

**Expected behavior**
Interop.UPNPLib should be included with Artalk.Xmpp ?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - VS 2019
 - .NET Standard 2.0

**Comment by ammarheidari** [comment]
Added Interop.UPNPLib.dll to root. Please check and download it manually.
