### ISSUE TITLE
What steps needed to make this framework works with Jitsi?

### ISSUE THREAD

**Issue by GeorgeS2019** [araditc/Artalk.Xmpp#15]
I wonder if there is a possibility to use this framework to serve as client connecting to Jitsi meet 
Sorry for a brief remark. I have seen many questions asking for a .NET or C# way to connect to Jitsi to retrieve video and audio. I just found a website referring to this framework as a XMPP library, Perhaps some of you landing here also seeking similar questions.  Perhaps we can use this issue to start the discussion for a possible path for a XMPP client to Jitsi meet.

**Comment by ammarheidari** [comment]
Currently, we do not support voice and video calling. But we are happy for those who have the ability to help and add this opportunity as a developer
