### ISSUE TITLE
Create nuget package 2.0.0-beta001 (unstable one) to verify extensions feature

### ISSUE THREAD

**Issue by towa48** [araditc/Artalk.Xmpp#20]
**Is your feature request related to a problem? Please describe.**
Cannot use new feature throughout nuget lib

**Describe the solution you'd like**
Deploy nuget package

**Describe alternatives you've considered**

**Additional context**
Please create nuget package 2.0.0-beta001

**Comment by ammarheidari** [comment]
Nuget package updated
