### ISSUE TITLE
Server-to-server?

### ISSUE THREAD

**Issue by alexkozler** [araditc/Artalk.Xmpp#6]
Is there any way to do server-to-server communication with this library versus just acting as a client towards an existing server?

A company I'm working with has an existing remote server, their own set of users, and their own client app.

They want to direct some of their messages over to me (as if I had my own server). I'm not sure if this would work for that or not? The concept is kind of confusing to me.

**Comment by ammarheidari** [comment]
Hello
By this library you can send messages to any authorized server. S2S should support in both sides
