### ISSUE TITLE
 Authentication failed because the remote party has closed the transport stream

### ISSUE THREAD

**Issue by JMLOSP** [araditc/Artalk.Xmpp#8]
**Describe the bug**
Failed connection when trying to authenticate.  Authentication failed because the remote party has closed the transport stream

**To Reproduce**

 ```
            client = new ArtalkXmppClient(txtServer.Text, txtUsername.Text, txtPassword.Text);
            client.Tls = true;
            client.Message += OnNewMessage;
            client.Connect();
            btnConnect.Enabled = false;
            btnDisconnect.Enabled = true;
```

**Expected behavior**
Succesfull connection

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser 
 - Version

**Comment by canecatfisher** [comment]
Hi!

May be it will be useful. I bumbed into this bug too, but I noticed at least one server which works fine, and another one who closes connection, with completely the same client settings.

The connection is closed during initialization secure session, after the client says "Client Hello". The one difference between good and bad server I noticed is that in good session the client sends "Client Hello" with TLSv1 header, but in bad session it sends the same packet with "SSL" header. The both packets are the same "TLS 1.0 Handshake" content.

I am not sure, if it is correct to send "TLS 1.0 Handshake" with "SSL" header, not "TLSv1", but probably it startles the  server.

Also I tried to analyze code, but still have not understood why the client library sends "TLSv1" in one case but "SSL" in another case, and if it is possible to make it use "TLSv1" header in any case.

I hope it will help.


![ClientHello](https://user-images.githubusercontent.com/26085731/78579431-96ff3c80-7839-11ea-8b88-8f7228b27023.png)
![good-error-sessions](https://user-images.githubusercontent.com/26085731/78579440-98c90000-7839-11ea-8c56-b18f1df780bc.png)
